name: Build Maya Manager

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MinGW (64-bit)
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Build Maya Manager
      shell: cmd
      run: |
        g++ MayaWatchdog.cpp ^
        -o MayaManager.exe ^
        -static ^
        -static-libgcc ^
        -static-libstdc++ ^
        -mwindows ^
        -lws2_32 ^
        -luser32 ^
        -lgdi32 ^
        -lshell32

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MayaManager
        path: MayaManager.exe
